# coding: utf-8

# flake8: noqa
"""
    WILCO API

    This  API allows you to pull and push data with your WILCO deployment [https://github.com/flightwatching/wilco-api](https://github.com/flightwatching/wilco-api) or on  [www.flightwatching.com](www.flightwatching.com).   # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: contact@flightwatching.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.bookmark_v3_io import BookmarkV3IO
from swagger_client.models.constant_v3_io import ConstantV3IO
from swagger_client.models.dashboard_symbol_function_v3_io import DashboardSymbolFunctionV3IO
from swagger_client.models.dashboard_symbol_v3_io import DashboardSymbolV3IO
from swagger_client.models.dashboard_v3_io import DashboardV3IO
from swagger_client.models.error_dao import ErrorDao
from swagger_client.models.event_v3_io import EventV3IO
from swagger_client.models.ext_source import ExtSource
from swagger_client.models.fwot_v3_io import FwotV3IO
from swagger_client.models.iei_param_v3_io import IeiParamV3IO
from swagger_client.models.iei_v3_io import IeiV3IO
from swagger_client.models.ift_v3_io import IftV3IO
from swagger_client.models.layout_v3_io import LayoutV3IO
from swagger_client.models.map import Map
from swagger_client.models.parameter_v3_io import ParameterV3IO
from swagger_client.models.rule_v3_io import RuleV3IO
from swagger_client.models.sample_v3_io import SampleV3IO
from swagger_client.models.stats_v3_io import StatsV3IO
from swagger_client.models.string import String
from swagger_client.models.tag_v3_io import TagV3IO
from swagger_client.models.trend_bundle_v3_io import TrendBundleV3IO
from swagger_client.models.user_v3_io import UserV3IO
